# site settings

title: SynthSculptor
description: A dynamic gallery chronicling both ongoing and past projects.
taglong: Jekyll theme for a beautiful online CV
tagshort: Jekyll theme
url: https://darbumas.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/darbumas/username.github.io

# author settings

author:
  name: B. Bwashi
  email: bbwashi@outlook.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  github: darbumas
  linkedin: bbwashi
  twitter: darbumas

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
