# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SynthSculptor
email: bbwashi@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A dynamic gallery chronicling both ongoing and past projects. Each endeavor is
  a unique sculpture in the ever-evolving landscape of technology. Immerse
  yourself in the harmonious blend of algorithms and creativity, where every
  line of code resonates like notes in a grand composition. Explore the
  intersection of innovation and artistry at SynthSculptor, where software
  engineering becomes a captivating journey through digital landscapes.
domain: darbumas.github.io
baseurl: "" # the subpath of your site, e.g. /blog
url: https://darbumas.github.io
twitter_username: ""
github_username:  darbumas

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
